-- Application access goes through NestJS/Prisma, not the public data API.
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailVerification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "horses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "training_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "training_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trial_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "medical_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "injury_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "care_schedules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stalls" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "feeding_rations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stable_incidents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "race_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "race_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;

